const express = require('express');
const cors = require('cors');
const archiver = require('archiver');
const crypto = require('crypto');

const app = express();
app.use(cors());
app.use(express.json());

// In-memory store for generated projects
const projects = new Map();

app.post('/api/generate', (req, res) => {
    const { domain, requirements } = req.body;
    
    // "AI" Generation logic: We create a virtual file system structure based on domain
    const projectId = crypto.randomUUID();
    
    const files = {};
    
    // Add common files
    files['README.md'] = `# Generated Project\n\n**Domain:** ${domain}\n\n**Requirements:** \n${requirements}\n\nThis project was generated by ProjectForge AI!`;
    files['.gitignore'] = `node_modules/\n.env\ndist/\nbuild/\n`;
    
    if (domain === 'mern' || domain === 'fullstack' || domain === 'pern') {
        // Frontend
        files['frontend/package.json'] = JSON.stringify({ 
            name: "client", 
            version: "1.0.0", 
            scripts: { dev: "vite" }, 
            dependencies: { "react": "^18.2.0", "react-dom": "^18.2.0" },
            devDependencies: { "vite": "^4.0.0", "@vitejs/plugin-react": "^4.0.0" }
        }, null, 2);
        
        files['frontend/index.html'] = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Generated App</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`;
        
        files['frontend/src/main.jsx'] = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\n\nReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);`;
        
        files['frontend/src/App.jsx'] = `import React from 'react';\n\nfunction App() {\n  return (\n    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>\n      <h1>Generated App</h1>\n      <p><b>Domain:</b> ${domain}</p>\n      <p><b>Your Requirements:</b> ${requirements}</p>\n      <p>Start building your amazing idea here!</p>\n    </div>\n  );\n}\n\nexport default App;`;
        
        // Backend
        const dbCode = domain === 'mern' ? 
            `const mongoose = require('mongoose');\nmongoose.connect(process.env.MONGO_URI || 'mongodb://localhost/test');\nconsole.log('MongoDB connected');` : 
            domain === 'pern' ? 
            `const { Pool } = require('pg');\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\nconsole.log('PostgreSQL connected');` :
            `console.log('Database connected');`;

        files['backend/package.json'] = JSON.stringify({ 
            name: "server", 
            version: "1.0.0", 
            scripts: { dev: "node server.js" }, 
            dependencies: { "express": "^4.18.2", "cors": "^2.8.5", "dotenv": "^16.0.3" } 
        }, null, 2);
        
        files['backend/server.js'] = `require('dotenv').config();\nconst express = require('express');\nconst cors = require('cors');\nconst app = express();\n\napp.use(cors());\napp.use(express.json());\n\n${dbCode}\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'ok', message: 'API running!' });\n});\n\nconst PORT = process.env.PORT || 5000;\napp.listen(PORT, () => console.log('Server running on port ' + PORT));`;
        
    } else if (domain === 'python') {
        files['requirements.txt'] = `Django==4.2.1\ndjangorestframework==3.14.0\n`;
        files['manage.py'] = `# Django manage.py boilerplate\nimport os\nimport sys\n\ndef main():\n    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')\n    try:\n        from django.core.management import execute_from_command_line\n    except ImportError as exc:\n        raise ImportError("Couldn't import Django.") from exc\n    execute_from_command_line(sys.argv)\n\nif __name__ == '__main__':\n    main()`;
        files['README.md'] += `\n\n## Python Setup\nRun \`pip install -r requirements.txt\``;
    } else {
        // Generic setup
        files['package.json'] = JSON.stringify({ name: "app", version: "1.0.0" }, null, 2);
        files['index.js'] = `console.log("App running. Requirements:", "${requirements}");`;
    }

    projects.set(projectId, files);
    
    // Keep in memory for 10 minutes, then clear
    setTimeout(() => {
        projects.delete(projectId);
    }, 10 * 60 * 1000);
    
    // Simulate generation time
    setTimeout(() => {
        res.json({ projectId, message: "Project generated successfully." });
    }, 1000);
});

app.get('/api/download/:projectId', (req, res) => {
    const projectId = req.params.projectId;
    const files = projects.get(projectId);
    
    if (!files) {
        return res.status(404).send('Project not found or expired.');
    }

    res.attachment(`project-${projectId.substring(0, 6)}.zip`);
    const archive = archiver('zip', { zlib: { level: 9 } });
    
    archive.on('error', (err) => {
        res.status(500).send({ error: err.message });
    });
    
    archive.pipe(res);
    
    // Append files to archive
    for (const [filePath, content] of Object.entries(files)) {
        archive.append(content, { name: filePath });
    }
    
    archive.finalize();
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
