require('dotenv').config();
const express = require('express');
const cors = require('cors');
const archiver = require('archiver');
const crypto = require('crypto');
const { OpenAI } = require('openai');

const app = express();
app.use(cors());
app.use(express.json());

// In-memory store for generated projects
const projects = new Map();

// Supported hardcoded frameworks
const SUPPORTED_FRAMEWORKS = ['mern', 'fullstack', 'pern', 'python'];

app.post('/api/generate', async (req, res) => {
    const { domain, requirements } = req.body;
    const projectId = crypto.randomUUID();
    let files = {};

    try {
        // If domain isn't in our hardcoded frameworks, OR if we have an OpenAI key, use AI to generate!
        if (process.env.OPENAI_API_KEY) {
            console.log("Using OpenAI to generate project...");
            const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
            
            const prompt = `You are an expert AI software architect. The user wants a project for the domain: "${domain}".
            Their specific requirements are: "${requirements}".
            
            Generate a minimal but complete project scaffolding. 
            Return ONLY a valid JSON object where the keys are file paths (e.g. 'src/index.js', 'package.json', 'README.md') and values are the exact string contents of those files.
            Include a README.md that explains how to run it. Include basic necessary code to run a hello world of their requirement.
            DO NOT include markdown block formatting like \`\`\`json, just return the raw JSON object.`;
            
            const response = await openai.chat.completions.create({
                model: "gpt-4o",
                messages: [{ role: "user", content: prompt }],
                response_format: { type: "json_object" }
            });
            
            const aiContent = response.choices[0].message.content.trim();
            files = JSON.parse(aiContent);
            
        } else if (SUPPORTED_FRAMEWORKS.includes(domain)) {
            console.log("Using hardcoded templates for supported framework...");
            // Add common files
            files['README.md'] = `# Generated Project\n\n**Domain:** ${domain}\n\n**Requirements:** \n${requirements}\n\nThis project was generated by ProjectForge AI!`;
            files['.gitignore'] = `node_modules/\n.env\ndist/\nbuild/\n`;
            
            if (domain === 'mern' || domain === 'fullstack' || domain === 'pern') {
                // Frontend
                files['frontend/package.json'] = JSON.stringify({ 
                    name: "client", 
                    version: "1.0.0", 
                    scripts: { dev: "vite" }, 
                    dependencies: { "react": "^18.2.0", "react-dom": "^18.2.0" },
                    devDependencies: { "vite": "^4.0.0", "@vitejs/plugin-react": "^4.0.0" }
                }, null, 2);
                files['frontend/index.html'] = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Generated App</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>`;
                files['frontend/src/main.jsx'] = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App.jsx';\n\nReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><App /></React.StrictMode>);`;
                files['frontend/src/App.jsx'] = `import React from 'react';\n\nfunction App() {\n  return (\n    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>\n      <h1>Generated App</h1>\n      <p><b>Domain:</b> ${domain}</p>\n      <p><b>Your Requirements:</b> ${requirements}</p>\n      <p>Start building your amazing idea here!</p>\n    </div>\n  );\n}\n\nexport default App;`;
                
                // Backend
                const dbCode = domain === 'mern' ? 
                    `const mongoose = require('mongoose');\nmongoose.connect(process.env.MONGO_URI || 'mongodb://localhost/test');\nconsole.log('MongoDB connected');` : 
                    domain === 'pern' ? 
                    `const { Pool } = require('pg');\nconst pool = new Pool({ connectionString: process.env.DATABASE_URL });\nconsole.log('PostgreSQL connected');` :
                    `console.log('Database connected');`;

                files['backend/package.json'] = JSON.stringify({ 
                    name: "server", 
                    version: "1.0.0", 
                    scripts: { dev: "node server.js" }, 
                    dependencies: { "express": "^4.18.2", "cors": "^2.8.5", "dotenv": "^16.0.3" } 
                }, null, 2);
                files['backend/server.js'] = `require('dotenv').config();\nconst express = require('express');\nconst cors = require('cors');\nconst app = express();\n\napp.use(cors());\napp.use(express.json());\n\n${dbCode}\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'ok', message: 'API running!' });\n});\n\nconst PORT = process.env.PORT || 5000;\napp.listen(PORT, () => console.log('Server running on port ' + PORT));`;
            } else if (domain === 'python') {
                files['requirements.txt'] = `Django==4.2.1\ndjangorestframework==3.14.0\n`;
                files['manage.py'] = `# Django manage.py boilerplate\nimport sys\n# ...`;
                files['README.md'] += `\n\n## Python Setup\nRun \`pip install -r requirements.txt\``;
            }
        } else {
            console.log("No OpenAI key and domain not supported, falling back to basic generic template...");
            files['package.json'] = JSON.stringify({ name: "app", version: "1.0.0" }, null, 2);
            files['README.md'] = `# ${domain} App\n\nRequirements: ${requirements}\n\n**NOTE:** Add an \`OPENAI_API_KEY\` in \`server/.env\` to enable true AI-powered generation for custom domains!`;
            files['index.js'] = `console.log("App running. Requirements:", "${requirements}");`;
        }

        projects.set(projectId, files);
        
        // Keep in memory for 10 minutes, then clear
        setTimeout(() => { projects.delete(projectId); }, 10 * 60 * 1000);
        
        res.json({ projectId, message: "Project generated successfully." });

    } catch (error) {
        console.error("Generation Error:", error);
        res.status(500).json({ error: "Failed to generate project. If using OpenAI, check your API key." });
    }
});

app.get('/api/download/:projectId', (req, res) => {
    const projectId = req.params.projectId;
    const files = projects.get(projectId);
    
    if (!files) {
        return res.status(404).send('Project not found or expired.');
    }

    res.attachment(`project-${projectId.substring(0, 6)}.zip`);
    const archive = archiver('zip', { zlib: { level: 9 } });
    
    archive.on('error', (err) => { res.status(500).send({ error: err.message }); });
    archive.pipe(res);
    
    for (const [filePath, content] of Object.entries(files)) {
        archive.append(content, { name: filePath });
    }
    archive.finalize();
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
